#!/usr/bin/env bash
#transfer file to remote server

if [ "$#" -lt 3 ]
then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME [PATH_TO_SSH_KEY]"
    exit 1
fi

PATH_TO_FILE="$1"
IP="$2"
USERNAME="$3"
PATH_TO_KEY="$4"

scp -o StrictHostKeyChecking=no -i "$PATH_TO_KEY" "$PATH_TO_FILE" "$USERNAME"@"$IP":~/


