#!/usr/bin/env bash
#installing nginx 

sudo apt-get update -y
sudo apt-get install nginx -y
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
echo "<!DOCTYPE html><html><head><title>Hello World!</title></head><body><h1>Hello World!</h1></body></html>" > /var/www/html/index.html


service nginx start
