#!/usr/bin/env bash
#installing nginx 

sudo apt-get update -y
sudo apt-get install nginx -y
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
echo "Hello World!" > /var/www/html/index.nginx-debian.html

service nginx start
