#!/usr/bin/env bash
#script that print certain str at a 5 mul or 3mul or both
str="FizzBuzz"
str1="Fizz"
str2="Buzz"
i=1

while [ $i -le 100 ]
do
        if (( i % 3 == 0 )) && (( i % 5 == 0 )); then
                echo "$str"
        elif (( i % 3 == 0 )); then
                echo "$str1"
        elif (( i % 5 == 0 )); then
                echo "$str2"
        else
                echo "$i"
        fi
        ((i++))
done
 
