#!/usr/bin/env bash
#script to print str in bash using while and if statement
str="Best School"
str9="Hi"
i=0
while [ $i -lt 11 ]
do
if [ $i -eq 9 ]
then
	echo "$str9"
	((i++))
else
	echo "$str"
	((i++))
fi
done
