#!/usr/bin/env bash
#using while and case bash script displaying numbers from 1 to 20
str1="bad luck from China"
str2="bad luck from Japan"
str3="bad luck from Italy"
i=1
while [ $i -le 20 ]
do
	case $i in
	4 ) echo "$str1" ;;
	9 ) echo "$str2" ;;
	17 ) echo "$str3" ;;
	* ) echo "$i" ;;
	esac
	((i++))
done
