#!/bin/bash

command=/usr/bin/htop

if [ -f $command ]
then
	echo "$command is available, let run it..."
else
	echo "$command Not available ,installing it..."
	sudo apt update && sudo apt install -y htop
fi

$command
